# .streamlit/secrets.toml
SUPABASE_URL = "https://hhwhkgoxdiqgdsassqom.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhod2hrZ294ZGlxZ2RzYXNzcW9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2NjYyNDIsImV4cCI6MjA5MzI0MjI0Mn0.zp_K7veyF8fi-wQ2u7wNngqEOZEB1HEsrkN2mjPhwhY"